
export const CHANGE_COUNT = 'CHANGE_COUNT';
export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILE = 'GET_DATA_FAILE';


// topic
export const GET_TOPICDATA_REQUES = 'GET_TOPICDATA_REQUES';
export const GET_TOPICDATA_SUCCESS = 'GET_TOPICDATA_SUCCESS';
export const GET_TOPICDATA_FAILE = 'GET_TOPICDATA_FAILE';
